### ISSUE TITLE
some data are not cached

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#235]
Steps to reproduce:
- open app with network connection and make sure data is loaded for all elements in de timeline on the landing page
- go to one of the detail views, make sure that both the data layer and the OSM-background are loaded
- close app and deactivate all network connectivity
- open app
Result:
- data for `Current` and the past (yesterday, 2 days ago, etc.) are correctly retrieved from cache, the forecast are missing

![Screenshot_20200724-100055_BelAir_v2](https://user-images.githubusercontent.com/323719/88373030-60711180-cd97-11ea-8d04-b16225303ab2.jpg)

In the detail tab the OSM-background is missing, but the forecast values are correctly retrieved:
![Screenshot_20200724-100045_BelAir_v2](https://user-images.githubusercontent.com/323719/88373282-df664a00-cd97-11ea-8656-696be746621e.jpg)

**Comment by SpeckiJ** [comment]
This is probably caused by the second condition (`|| !this.lastValue`) in this line: https://github.com/irceline/aq-mobile-be/blob/762dea182ec61940aa7cf00f4ca868685bd5113f/src/app/v2/services/forecast-date.service.ts#L38

The App does store the time of the last forecast (from `timestring_forecast.php`) in the cache (only the data of the forecast itself) and tries to get it anew from the API when the App restarts. As this never succeeds the "Forecast Displayer" is stuck.

We need to cache the last forecast date to be able to retrieve the cached data, but assure that this never gets out-of-sync (e.g. the user closes the app for 2 days and opens it offline afterwards, we must detect that and invalidate the last forecast date as the forecast is actually unavailable (not cached as it was not available 2 days ago)).

**Comment by SpeckiJ** [comment]
This is not an issue for the past days as these are just calculated based on the current day, and not dynamically retrieved from the API.

**Comment by SpeckiJ** [comment]
I have added caching for the `lastValue` in https://github.com/irceline/aq-mobile-be/commit/1b8316dc4cfebfaba1cc7ecdf4ef4d5346e55151

Note: There are no forecasts displayed when the App is started offline for and no data has been fetched on that day (e.g. I fetch everything today and then turn off network until tomorrow and start the app tomorrow still without connection). In the caching logic the server response for "today + 3" is not equal to "tomorrow+2" and therefore cannot be used for any forecasts tomorrow.

**Comment by opeeters** [comment]
Something seems to go wrong.
This is what I get:
1) open app and make sure data for the timeline is loaded with network
2) got to e.g. the ozone tab and make sure all data is loaded (today, yesterday etc)
3) with the app still open deactivate network: on the general timeline and the ozone tab everything is fine and reactive
4) close the app and launch it again: no general timeline for any location and it is not possible to got to the ozone detail tab

**Comment by SpeckiJ** [comment]
Note: Make sure that one is requesting data for the same locations. I debugged it a lot and after an embarassingly long time I found that the App chooses some new random places every time I reopen the app, and ofc there is no cache data for these new locations.

**Comment by SpeckiJ** [comment]
I have fixed an error with javascript type confusion in https://github.com/irceline/aq-mobile-be/commit/f7d5ab10f6f0ad80b6735504ff1c42ca7b82727b. Apparently Date can also be String without any compilation problems... 

Note: There is currently no "Offline Warning" in the App like in v1, it can be confusing why e.g. data is shown but maps are not loading. There is also no hint that this is cached data that might be out-of-date.

**Comment by opeeters** [comment]
This looks much better, but in the detail the wms-layers for `current`, `yesterday` and `2 days ago` are correctly retrieved from cache when the device is not connected to any network. All the forecast layers (`today`, `tomorrow`, etc.) are however still missing.
